### ISSUE TITLE
Automatically enable `--color` if in a TTY

### ISSUE THREAD

**Issue by tasn** [svixhq/svix-cli#7]
There's a way to detect whether we are in a TTY or a script. If we are in a TTY we should have color on by default. It's just too good to not have on. :)

**Comment by svix-frank** [comment]
I'll deff add this! For now you can add `color = true` to your `~/.config/svix/config.toml` to have it enabled by default =)

**Comment by tasn** [comment]
Thanks for the pro-tip!
